<aside id="sidebar">
	<a href="https://github.com/kriztan/Pix-Art-Messenger" target="__blank" class="button"><small>Projekt auf</small>GitHub<small>betrachten</small></a>
	<a href="https://raw.githubusercontent.com/kriztan/Pix-Art-Messenger/master/CHANGELOG.md" target="__blank" class="button">&Auml;nderungen anzeigen</a>
	<a rel="me" href="https://social.tchncs.de/@pixart">Pix-Art Messenger bei Mastodon</a>
	<p class="repo-owner"><a href="https://github.com/kriztan/Pix-Art-Messenger" target="_blank"></a> wird betrieben von <a href="https://github.com/kriztan" target="_blank">Christian&nbsp;Schneppe</a>.</p>
	<p>This page was generated by <a href="https://pages.github.com" target="_blank">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong" target="_blank">Jason Long</a>.</p>
</aside>
